# Default serving configuration
checkpoint_path: /app/models/model.pt
confidence_threshold: 0.25

model:
  class_path: ml.src.objdet.models.yolo.YOLOv8
  init_args:
    model_name: yolov8n.pt
    task: detect

input:
  class_path: ml.src.objdet.serving.input.ImageInput
  init_args:
    shape: [640, 640]

server:
  port: 8000
